baseURL = 'https://weeks.mcgarity.me/'
languageCode = 'en-us'
title = 'My Life in Weeks'
disableKinds = ["taxonomy", "taxonomy"]
enableEmoji = true


[params]
author = "Matthew McGarity"

[caches]
  [caches.images]
    dir = ':cacheDir/images'